const API = "http://localhost:8080/";

const API_SUB_ROUTES = {
  AUTH: "auth/",
  ADMIN: "admin/",
  STUDENT: "student/",
  NOTE: "note/",
};

const ENDPOINTS = {
  CREDENTIALS: "credentials",
  AUTHORIZE: "authorize",
  SEARCH: "search",
  CREATE: "create",
  NOTE: "note",
  NOTES: "notes",
  USERS: "users",
  UPDATE: "update",
};

export const API_ROUTES = {
  CREDENTIALS: API + API_SUB_ROUTES.AUTH + ENDPOINTS.CREDENTIALS,
  PROFILE_UPDATE: API + API_SUB_ROUTES.AUTH + ENDPOINTS.UPDATE,
  AUTHORIZATION: API + API_SUB_ROUTES.AUTH + ENDPOINTS.AUTHORIZE,
  ADMIN_CREATE: API + API_SUB_ROUTES.ADMIN + ENDPOINTS.CREATE,
  ADMIN_GET_USERS: API + API_SUB_ROUTES.ADMIN + ENDPOINTS.USERS,
  ADMIN_SEARCH: API + API_SUB_ROUTES.ADMIN + ENDPOINTS.SEARCH,
  STUDENT_NOTE: API + API_SUB_ROUTES.STUDENT + ENDPOINTS.NOTE,
  STUDENT_NOTES: API + API_SUB_ROUTES.STUDENT + ENDPOINTS.NOTES,
  STUDENT_NOTES_UPDATE: API + API_SUB_ROUTES.NOTE + ENDPOINTS.UPDATE,
};
